module QuantumCumulantsExt

using QuantumCumulants
using QuantumCumulants: FockSpace, NLevelSpace, PauliSpace, ProductSpace, Destroy, Create, Transition, Pauli
const SQA = QuantumCumulants.SecondQuantizedAlgebra

using QuantumSymbolics
using QuantumSymbolics:
    Symbolic, QuantumCumulantsRepr,
    XGate, YGate, ZGate, HGate, PauliP, PauliM,
    ZBasisState,
    NumberOp, CreateOp, DestroyOp,
    IdentityOp, SZeroOperator,
    SProjector, SOuterKetBra, SDagger, SConjugate, STranspose,
    SCommutator, SAnticommutator, STensor,
    qubit_basis
import QuantumSymbolics: express, express_nolookup

using QuantumInterface:
    AbstractBra, AbstractKet, AbstractOperator, AbstractSuperOperator,
    AbstractUse, Basis, CompositeBasis, FockBasis, NLevelBasis, SpinBasis, basis

##
# Deriving a QuantumCumulants Hilbert space from a QuantumSymbolics basis
##

subbases(b::CompositeBasis) = b.bases
subbases(b::Basis) = (b,)

"""Map a single (non-composite) QuantumSymbolics basis to a QuantumCumulants Hilbert space."""
qc_subspace(::FockBasis, name::Symbol) = FockSpace(name)
qc_subspace(b::NLevelBasis, name::Symbol) = NLevelSpace(name, b.N)
function qc_subspace(b::SpinBasis, name::Symbol)
    b == qubit_basis || throw(ArgumentError(lazy"Only two-level spin systems can be mapped to a QuantumCumulants Hilbert space, got $b"))
    NLevelSpace(name, (:g, :e))
end
qc_subspace(b::Basis, ::Symbol) = throw(ArgumentError(lazy"There is no QuantumCumulants Hilbert space corresponding to $b"))

default_name(::FockBasis) = :a
default_name(::SpinBasis) = :σ
default_name(::NLevelBasis) = :σ
default_name(b::Basis) = throw(ArgumentError(lazy"There is no QuantumCumulants Hilbert space corresponding to $b"))

"""Names for the subsystems of `bases`, disambiguated with a numeric suffix only when a
given kind of subsystem shows up more than once."""
function default_names(bases)
    stems = map(default_name, bases)
    counts = Dict{Symbol,Int}()
    for s in stems
        counts[s] = get(counts, s, 0) + 1
    end
    seen = Dict{Symbol,Int}()
    map(stems) do s
        counts[s] == 1 && return s
        seen[s] = get(seen, s, 0) + 1
        Symbol(s, seen[s])
    end
end

"""The QuantumCumulants Hilbert space matching the QuantumSymbolics basis `b`.

The subsystems are named after `names`, or with autogenerated names when `names===nothing`."""
function qc_hilbertspace(b::Basis, names=nothing)
    bases = subbases(b)
    nms = names === nothing ? default_names(bases) : collect(Symbol, names)
    length(nms) == length(bases) ||
        throw(ArgumentError(lazy"Got $(length(nms)) names for a system of $(length(bases)) subsystems"))
    spaces = map(qc_subspace, bases, nms)
    length(spaces) == 1 ? only(spaces) : ⊗(spaces...)
end

"""When the representation does not specify a Hilbert space, derive one from the basis of
the object being expressed and redo the conversion with it."""
function express(x::Symbolic, r::QuantumCumulantsRepr{Nothing}, use::AbstractUse)
    b = basis(x)
    b === nothing && return express_nolookup(x, r, use) # the symbolic zero needs no Hilbert space
    express(x, QuantumCumulantsRepr(qc_hilbertspace(b, r.names), r.names, r.aon), use)
end

##
# Locating the subsystem an object acts on
##

spaces(h::ProductSpace) = h.spaces
spaces(h::SQA.HilbertSpace) = (h,)

"""The subspace of `r.hilbertspace` that the object being expressed acts on."""
function subspace(r::QuantumCumulantsRepr)
    sp = spaces(r.hilbertspace)
    1 <= r.aon <= length(sp) ||
        throw(ArgumentError(lazy"Subsystem $(r.aon) is out of range for the Hilbert space $(r.hilbertspace)"))
    sp[r.aon]
end

"""The subspace `r` points at, checked to be of type `T`."""
function checked_subspace(r::QuantumCumulantsRepr, ::Type{T}) where {T<:SQA.HilbertSpace}
    s = subspace(r)
    s isa T || throw(ArgumentError(lazy"Subsystem $(r.aon) of $(r.hilbertspace) is a $(typeof(s)), but a $T is needed to express this object"))
    s
end

"""The name of the operator living on the subsystem `r` points at."""
function opname(r::QuantumCumulantsRepr)
    r.names === nothing && return subspace(r).name
    r.aon <= length(r.names) ||
        throw(ArgumentError(lazy"No operator name was given for subsystem $(r.aon)"))
    Symbol(r.names[r.aon])
end

"""Shift the subsystem index of `r` by `k`, used when recursing into tensor products."""
shift(r::QuantumCumulantsRepr, k::Int) = QuantumCumulantsRepr(r.hilbertspace, r.names, r.aon + k)

# The QuantumCumulants constructors take a subsystem index only for product spaces.
_destroy(r) = (h = r.hilbertspace; h isa ProductSpace ? Destroy(h, opname(r), r.aon) : Destroy(h, opname(r)))
_create(r) = (h = r.hilbertspace; h isa ProductSpace ? Create(h, opname(r), r.aon) : Create(h, opname(r)))
_transition(r, i::Int, j::Int) = (h = r.hilbertspace; h isa ProductSpace ? Transition(h, opname(r), i, j, r.aon) : Transition(h, opname(r), i, j))
_pauli(r, axis::Int) = (h = r.hilbertspace; h isa ProductSpace ? Pauli(h, opname(r), axis, r.aon) : Pauli(h, opname(r), axis))

"""The excited and ground level indices of a two-level `NLevelSpace`.

`QuantumSymbolics` orders the qubit basis states as `|0⟩ = Z₁` (spin up, the state `σ₊`
raises to) and `|1⟩ = Z₂` (spin down), so `Z₁` is identified with the excited level of the
`NLevelSpace` and `Z₂` with its ground level."""
function eglevels(s::NLevelSpace, r::QuantumCumulantsRepr)
    s.n == 2 || throw(ArgumentError(lazy"Qubit operators need a two-level NLevelSpace, but subsystem $(r.aon) of $(r.hilbertspace) has $(s.n) levels"))
    g = s.ground_state
    (3 - g, g) # (excited, ground)
end

##
# Bosonic modes
##

express_nolookup(::DestroyOp, r::QuantumCumulantsRepr) = (checked_subspace(r, FockSpace); _destroy(r))
express_nolookup(::CreateOp, r::QuantumCumulantsRepr) = (checked_subspace(r, FockSpace); _create(r))
express_nolookup(::NumberOp, r::QuantumCumulantsRepr) = (checked_subspace(r, FockSpace); _create(r) * _destroy(r))

##
# Two-level systems
#
# On an `NLevelSpace` qubit operators become transition operators `|i⟩⟨j|`,
# on a `PauliSpace` they become Pauli operators.
##

for gate in (:XGate, :YGate, :ZGate, :PauliP, :PauliM, :HGate)
    @eval express_nolookup(g::$gate, r::QuantumCumulantsRepr) = qubit_op(g, subspace(r), r)
end

qubit_op(g, s::SQA.HilbertSpace, r::QuantumCumulantsRepr) =
    throw(ArgumentError(lazy"Subsystem $(r.aon) of $(r.hilbertspace) is a $(typeof(s)), but an NLevelSpace or a PauliSpace is needed to express $g"))

function qubit_op(::XGate, s::NLevelSpace, r::QuantumCumulantsRepr)
    e, g = eglevels(s, r)
    _transition(r, e, g) + _transition(r, g, e)
end
function qubit_op(::YGate, s::NLevelSpace, r::QuantumCumulantsRepr)
    e, g = eglevels(s, r)
    im * (_transition(r, g, e) - _transition(r, e, g))
end
function qubit_op(::ZGate, s::NLevelSpace, r::QuantumCumulantsRepr)
    e, g = eglevels(s, r)
    _transition(r, e, e) - _transition(r, g, g)
end
function qubit_op(::PauliP, s::NLevelSpace, r::QuantumCumulantsRepr)
    e, g = eglevels(s, r)
    _transition(r, e, g)
end
function qubit_op(::PauliM, s::NLevelSpace, r::QuantumCumulantsRepr)
    e, g = eglevels(s, r)
    _transition(r, g, e)
end

qubit_op(::XGate, ::PauliSpace, r::QuantumCumulantsRepr) = _pauli(r, 1)
qubit_op(::YGate, ::PauliSpace, r::QuantumCumulantsRepr) = _pauli(r, 2)
qubit_op(::ZGate, ::PauliSpace, r::QuantumCumulantsRepr) = _pauli(r, 3)
qubit_op(::PauliP, ::PauliSpace, r::QuantumCumulantsRepr) = (_pauli(r, 1) + im * _pauli(r, 2)) / 2
qubit_op(::PauliM, ::PauliSpace, r::QuantumCumulantsRepr) = (_pauli(r, 1) - im * _pauli(r, 2)) / 2

qubit_op(::HGate, s::Union{NLevelSpace,PauliSpace}, r::QuantumCumulantsRepr) =
    (qubit_op(XGate(), s, r) + qubit_op(ZGate(), s, r)) / √2

##
# Projectors and outer products of qubit basis states
##

_asket(x::SDagger) = x.obj
_asket(x) = x

express_nolookup(x::SProjector, r::QuantumCumulantsRepr) = outer(x.ket, x.ket, subspace(r), r)
express_nolookup(x::SOuterKetBra, r::QuantumCumulantsRepr) = outer(x.ket, _asket(x.bra), subspace(r), r)

outer(k, b, s::SQA.HilbertSpace, r::QuantumCumulantsRepr) =
    throw(ArgumentError(lazy"Subsystem $(r.aon) of $(r.hilbertspace) is a $(typeof(s)), but an NLevelSpace or a PauliSpace is needed to express |$k⟩⟨$b|"))

function outer(k::ZBasisState, b::ZBasisState, s::NLevelSpace, r::QuantumCumulantsRepr)
    # only two-level systems carry the spin up/down convention that has to be undone;
    # for more levels the basis states are numbered the same way in both packages
    s.n == 2 || return _transition(r, k.idx, b.idx)
    e = eglevels(s, r)
    _transition(r, e[k.idx], e[b.idx])
end
function outer(k::ZBasisState, b::ZBasisState, s::PauliSpace, r::QuantumCumulantsRepr)
    k.idx == b.idx && return (1 + (k.idx == 1 ? 1 : -1) * _pauli(r, 3)) / 2
    qubit_op(k.idx == 1 ? PauliP() : PauliM(), s, r)
end

##
# Composite expressions
##

express_nolookup(::SZeroOperator, ::QuantumCumulantsRepr) = 0
express_nolookup(::IdentityOp, ::QuantumCumulantsRepr) = 1

"""Number of subsystems an object spans, used to lay out the factors of a tensor product
over the subsystems of the QuantumCumulants Hilbert space."""
nsubsystems(x) = length(subbases(basis(x)))

function express_nolookup(x::STensor{AbstractOperator}, r::QuantumCumulantsRepr)
    factors = []
    offset = 0
    for t in x.terms
        f = express(t, shift(r, offset))
        # dropping the identity factors keeps a single-operator product a bare
        # QuantumCumulants operator instead of a one-term sum
        (f isa Number && isone(f)) || push!(factors, f)
        offset += nsubsystems(t)
    end
    isempty(factors) ? 1 : reduce(*, factors)
end

# The `commutator`, `anticommutator` and `dagger` of QuantumSymbolics are different
# functions from the identically named ones of QuantumCumulants, so the generic
# `express_nolookup` fallback (which simply reapplies `operation(x)`) does not work here.
express_nolookup(x::SCommutator, r::QuantumCumulantsRepr) =
    (a = express(x.op1, r); b = express(x.op2, r); a * b - b * a)
express_nolookup(x::SAnticommutator, r::QuantumCumulantsRepr) =
    (a = express(x.op1, r); b = express(x.op2, r); a * b + b * a)
express_nolookup(x::SDagger{AbstractOperator}, r::QuantumCumulantsRepr) = adjoint(express(x.obj, r))

# Complex conjugation and transposition are basis dependent and have no counterpart in the
# basis-free algebra of QuantumCumulants; without these methods they would fail with an
# opaque `MethodError` from the generic `express_nolookup` fallback.
express_nolookup(x::Union{SConjugate{AbstractOperator},STranspose{AbstractOperator}}, ::QuantumCumulantsRepr) =
    throw(ArgumentError(lazy"QuantumCumulants operators are basis free, so the basis dependent $x can not be expressed in it (`dagger` can be)"))

express_nolookup(x::Symbolic{<:Union{AbstractKet,AbstractBra}}, ::QuantumCumulantsRepr) =
    throw(ArgumentError(lazy"QuantumCumulants is an operator algebra with no notion of state vectors, so $x can not be expressed in it (the projector `projector($x)` can be)"))
express_nolookup(x::Symbolic{AbstractSuperOperator}, ::QuantumCumulantsRepr) =
    throw(ArgumentError(lazy"QuantumCumulants has no notion of superoperators, so $x can not be expressed in it"))

end
